In [1]:
import numpy

In [6]:
import math

In [3]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [4]:
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [7]:
# how to create vector in matrices
print(dir(numpy.ndarray))


['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [9]:
#vector....
import numpy as np
vec = [234,3,45,3,45,4,34,54,3,45,3,45]
arr = np.array(vec);arr

array([234,   3,  45,   3,  45,   4,  34,  54,   3,  45,   3,  45])

In [10]:
arr[0:5]

array([234,   3,  45,   3,  45])

In [11]:
vec1 = [234,3,45,3,45,4,34,54,3,45,3,'mango',45]
arr1 = np.array(vec1,dtype = 'str');arr1

array(['234', '3', '45', '3', '45', '4', '34', '54', '3', '45', '3',
       'mango', '45'], dtype='<U5')

In [12]:
# create multi nested array

lst1 = [12,34,5,23]
lst2 = [13,14,5,23]
lst3 = [12,39,5,24]
lst4 = [10,14,51,23]

arr2 = np.array([[lst1,lst2,lst3,lst4]]);arr2


array([[[12, 34,  5, 23],
        [13, 14,  5, 23],
        [12, 39,  5, 24],
        [10, 14, 51, 23]]])

In [13]:
arr2*2

array([[[ 24,  68,  10,  46],
        [ 26,  28,  10,  46],
        [ 24,  78,  10,  48],
        [ 20,  28, 102,  46]]])

In [14]:
arr2.shape

(1, 4, 4)

In [15]:
arr2[0][0].shape

(4,)

In [16]:
arr2[0]

array([[12, 34,  5, 23],
       [13, 14,  5, 23],
       [12, 39,  5, 24],
       [10, 14, 51, 23]])

In [25]:
arr2[0][3][2]

51

In [26]:
arr2[0][0][0:2] = 100

In [27]:
arr2

array([[[100, 100,   5,  23],
        [ 13,  14,   5,  23],
        [ 12,  39,   5,  24],
        [ 10,  14,  51,  23]]])